= Effective Testing for Quarkus Applications
2023-04-18

- ✓ Test Principles & Constraints
  - execute fast, provide fast feedback
    code level tests, per hundreds < 1s
    integrative system test, per test ideally < 1s
  - fast development feedback, no startup costs between test runs, turnaround time < 5s
  - ability to refactor production code without significant test refactoring effort
  - changes in functional behavior should only result in minimal test code changes
  - ability to craft proper abstraction layers / delegation, tailed to domain
  - ability to support hot-reload development modes
  - compatibility with running & configuring test environment individually
  - reusability of test components (technical & functional) for multiple scenarios
- ✓ Test Scopes
  Code-level unit tests, Code-level use case / component tests, Code-level integration tests, system / acceptance tests
- ✓ Code-Level Tests
  JUnit, Mockito, AssertJ, Parameterized Tests
  https://junit.org/junit5/docs/current/user-guide/
- ✓ Use Case Tests, Component Tests (code-level)
- ✓ Code-Level Integration Tests
  @QuarkusTest yes or no?
- ✓ System / Acceptance Tests
  Testcontainers
- ✓ Effective Testing Workflows, TDD
  Separation of test scenario and test environment
  Experimental: running quarkus:dev for non-Quarkus projects: `mvn -P test quarkus:dev` (in coffee-shop-st)
- ✓ Test Isolation & Idempotency
- ✓ Local Development, IDEs, Build Tooling, Maven
  Maven Integration Tests (*IT): `mvn test-compile failsafe:integration-test failsafe:verify`
  Quarkus dev include all tests: `mvn -Dquarkus.test.exclude-pattern='' quarkus:dev`
  Quarkus dev include specific test: `mvn -Dquarkus.test.include-pattern='.*TestName' quarkus:dev`
- ✓ Databases, Test Data, Data Migration
- ✓ CI/CD Pipelines and Testing
- ✓ Test Code Quality & Maintainable Tests
- ✓ UI tests, Selenium, Selenide
- ✓ JVM Test Frameworks
- ✓ AssertJ Custom Assertions
- ✓ Test Coverage, JaCoCo
  https://quarkus.io/guides/tests-with-coverage
  https://blog.sebastian-daschner.com/entries/jacoco-system-test-coverage


== Running the examples

You run the environment, containing the _coffee-shop_, _barista_ applications and the _coffee-shop-db_ using Docker containers with the provided scripts.

In order to run the Docker containers locally, you need to create a Docker network first: + 
`docker network create --subnet=192.168.42.0/24 dkrnet`
